
import { AnimalInfo, Conflicto, MemoriaLugar, NecesidadBiologica, FlorBach, ComandoEspecifico, InstintoPrimario, CausaBloqueo, ZonaHogar, TipoTraumaGeneral, CronologiaTrauma } from './types';

export const TITULO_APP = "Manual Completo de Diagnóstico Radiónico para Animales";
export const VERSION_APP = "Versión 4.0 - Edición Trauma Integrada | Morphic Field Therapy® | 2025"; 

export const ESPECIES_ANIMALES: AnimalInfo['especie'][] = ['Perro', 'Gato', 'Ave', 'Conejo', 'Caballo', 'Otro'];
export const SEXO_OPCIONES: AnimalInfo['sexo'][] = ['Macho', 'Hembra', 'Desconocido'];
export const ESTADO_REPRODUCTIVO_OPCIONES: AnimalInfo['estadoReproductivo'][] = ['Entero', 'Castrado/Esterilizado', 'Desconocido'];
export const AMBIENTE_ACTUAL_OPCIONES: AnimalInfo['ambienteActual'][] = ['Urbano', 'Rural', 'Mixto', 'Otro'];
export const HISTORIA_PREVIA_OPCIONES: AnimalInfo['historiaPrevia'][] = ['Rescate', 'Compra', 'Nacimiento en casa', 'Desconocida', 'Otro'];

// --- DATOS PARA DIAGNÓSTICO DE INSTINTOS BLOQUEADOS (Manual V4.0, P.3-5) ---
export const INSTINTOS_PRIMARIOS_DATA: InstintoPrimario[] = [
  // PERROS (P.3)
  { id: 'IPD1', especieAnimal: ['Perro'], nombreInstinto: 'Jerarquía de Manada', funcionNatural: 'Saber su lugar en el grupo social', manifestacionSana: 'Respeto sin sumisión, liderazgo equilibrado', distorsionDomestica: 'Dominancia agresiva o sumisión patológica', preguntaTesteo: '¿El instinto de jerarquía está bloqueado/distorsionado?', fuenteManual: "P.3, P.8" },
  { id: 'IPD2', especieAnimal: ['Perro'], nombreInstinto: 'Caza Cooperativa', funcionNatural: 'Trabajar en equipo para obtener alimento', manifestacionSana: 'Juego constructivo, colaboración', distorsionDomestica: 'Destrucción de objetos, ansiedad por comida', preguntaTesteo: '¿El instinto de caza cooperativa está bloqueado?', fuenteManual: "P.3, P.9" },
  { id: 'IPD3', especieAnimal: ['Perro'], nombreInstinto: 'Protección Territorial', funcionNatural: 'Defender el espacio del grupo', manifestacionSana: 'Alerta apropiada, valentía selectiva', distorsionDomestica: 'Agresividad indiscriminada o miedo extremo', preguntaTesteo: '¿El instinto de protección está bloqueado/hiperactivado?', fuenteManual: "P.3, P.9" },
  { id: 'IPD4', especieAnimal: ['Perro'], nombreInstinto: 'Comunicación de Manada', funcionNatural: 'Expresar necesidades y estados', manifestacionSana: 'Ladrido funcional, lenguaje corporal claro', distorsionDomestica: 'Ladrido compulsivo, comunicación confusa', preguntaTesteo: '¿El instinto de comunicación está distorsionado?', fuenteManual: "P.3, P.9" },
  { id: 'IPD5', especieAnimal: ['Perro'], nombreInstinto: 'Exploración Grupal', funcionNatural: 'Conocer el territorio en grupo', manifestacionSana: 'Paseos tranquilos, curiosidad sana', distorsionDomestica: 'Ansiedad de separación, hipervigilancia', preguntaTesteo: '¿El instinto de exploración está bloqueado?', fuenteManual: "P.3, P.9" },
  { id: 'IPD6', especieAnimal: ['Perro'], nombreInstinto: 'Trabajo con Propósito', funcionNatural: 'Cumplir función específica en manada', manifestacionSana: 'Tareas constructivas, satisfacción personal', distorsionDomestica: 'Aburrimiento, comportamientos destructivos', preguntaTesteo: '¿El instinto de trabajo está frustrado?', fuenteManual: "P.3, P.9" },
  
  // GATOS (P.3-4)
  { id: 'IPG1', especieAnimal: ['Gato'], nombreInstinto: 'Caza Solitaria', funcionNatural: 'Obtener alimento de manera independiente', manifestacionSana: 'Juego de acecho, satisfacción personal', distorsionDomestica: 'Agresividad hacia otros animales, frustración', preguntaTesteo: '¿El instinto de caza está bloqueado/frustrado?', fuenteManual: "P.3-4" },
  { id: 'IPG2', especieAnimal: ['Gato'], nombreInstinto: 'Territorialidad Vertical', funcionNatural: 'Controlar territorio desde las alturas', manifestacionSana: 'Uso de repisas, observación desde altura', distorsionDomestica: 'Ansiedad por falta de espacios altos', preguntaTesteo: '¿El instinto territorial vertical está bloqueado?', fuenteManual: "P.4" },
  { id: 'IPG3', especieAnimal: ['Gato'], nombreInstinto: 'Ciclos Crepusculares', funcionNatural: 'Actividad al amanecer y atardecer', manifestacionSana: 'Energía natural en estas horas', distorsionDomestica: 'Hiperactividad nocturna descontrolada', preguntaTesteo: '¿Los ciclos naturales están alterados?', fuenteManual: "P.4" },
  { id: 'IPG4', especieAnimal: ['Gato'], nombreInstinto: 'Autosuficiencia', funcionNatural: 'Resolver problemas sin ayuda externa', manifestacionSana: 'Confianza en sus capacidades', distorsionDomestica: 'Dependencia excesiva o aislamiento total', preguntaTesteo: '¿El instinto de independencia está comprometido?', fuenteManual: "P.4" },
  { id: 'IPG5', especieAnimal: ['Gato'], nombreInstinto: 'Marcaje Territorial', funcionNatural: 'Comunicar presencia a otros felinos', manifestacionSana: 'Marcaje apropiado en lugares designados', distorsionDomestica: 'Marcaje inadecuado o comportamiento territorial extremo', preguntaTesteo: '¿El instinto de marcaje está distorsionado?', fuenteManual: "P.4" },
  { id: 'IPG6', especieAnimal: ['Gato'], nombreInstinto: 'Vigilancia desde Altura', funcionNatural: 'Observar territorio desde posición elevada', manifestacionSana: 'Uso natural de espacios altos', distorsionDomestica: 'Estrés por falta de observatorios seguros', preguntaTesteo: '¿El instinto de observación está frustrado?', fuenteManual: "P.4" },

  // AVES (P.4)
  { id: 'IPA1', especieAnimal: ['Ave'], nombreInstinto: 'Vida de Bandada', funcionNatural: 'Socialización con su especie', manifestacionSana: 'Comunicación vocal rica, comportamiento social', distorsionDomestica: 'Gritos excesivos, comportamiento antisocial', preguntaTesteo: '¿El instinto de vida en bandada está frustrado?', fuenteManual: "P.4" },
  { id: 'IPA2', especieAnimal: ['Ave'], nombreInstinto: 'Migración y Vuelo', funcionNatural: 'Movimiento libre en tres dimensiones', manifestacionSana: 'Ejercicio de alas, exploración activa', distorsionDomestica: 'Automutilación, comportamientos repetitivos', preguntaTesteo: '¿El instinto de vuelo está bloqueado?', fuenteManual: "P.4" },
  { id: 'IPA3', especieAnimal: ['Ave'], nombreInstinto: 'Construcción de Nido', funcionNatural: 'Crear espacios seguros para reproducción', manifestacionSana: 'Comportamientos de anidación apropiados', distorsionDomestica: 'Destrucción compulsiva o acumulación', preguntaTesteo: '¿El instinto de construcción de nido está frustrado?', fuenteManual: "P.4" },
  { id: 'IPA4', especieAnimal: ['Ave'], nombreInstinto: 'Comunicación Vocal', funcionNatural: 'Expresar estados y necesidades complejas', manifestacionSana: 'Vocalización variada y funcional', distorsionDomestica: 'Gritos monótonos o silencio total', preguntaTesteo: '¿La comunicación vocal está distorsionada?', fuenteManual: "P.4" },
  { id: 'IPA5', especieAnimal: ['Ave'], nombreInstinto: 'Forrajeo', funcionNatural: 'Buscar alimento de manera activa', manifestacionSana: 'Exploración y manipulación de objetos', distorsionDomestica: 'Aburrimiento, falta de estimulación', preguntaTesteo: '¿El instinto de forrajeo está bloqueado?', fuenteManual: "P.4" },
  { id: 'IPA6', especieAnimal: ['Ave'], nombreInstinto: 'Jerarquía Social (Aves)', funcionNatural: 'Establecer orden en grupo', manifestacionSana: 'Interacciones equilibradas', distorsionDomestica: 'Dominancia agresiva o sumisión extrema', preguntaTesteo: '¿La jerarquía social está desequilibrada?', fuenteManual: "P.5 (implícito)" },
  
  // CONEJOS (P.5)
  { id: 'IPC1', especieAnimal: ['Conejo'], nombreInstinto: 'Vigilancia Constante', funcionNatural: 'Detectar predadores desde múltiples direcciones', manifestacionSana: 'Alerta relajada, respuesta apropiada', distorsionDomestica: 'Hipervigilancia, estrés constante', preguntaTesteo: '¿El instinto de vigilancia está hiperactivado o ausente?', fuenteManual: "P.5" },
  { id: 'IPC2', especieAnimal: ['Conejo'], nombreInstinto: 'Excavación', funcionNatural: 'Crear túneles y madrigueras', manifestacionSana: 'Comportamientos de excavación controlados', distorsionDomestica: 'Destrucción de alfombras, frustración', preguntaTesteo: '¿El instinto de excavación está bloqueado?', fuenteManual: "P.5" },
  { id: 'IPC3', especieAnimal: ['Conejo'], nombreInstinto: 'Vida de Grupo', funcionNatural: 'Socialización jerárquica con otros conejos', manifestacionSana: 'Interacción social equilibrada', distorsionDomestica: 'Agresividad territorial o aislamiento', preguntaTesteo: '¿El instinto de vida de grupo está afectado?', fuenteManual: "P.5" },
  { id: 'IPC4', especieAnimal: ['Conejo'], nombreInstinto: 'Alimentación Selectiva', funcionNatural: 'Elegir plantas apropiadas para digestión', manifestacionSana: 'Selección cuidadosa de alimentos', distorsionDomestica: 'Problemas digestivos, alimentación compulsiva', preguntaTesteo: '¿El instinto de alimentación selectiva está alterado?', fuenteManual: "P.5" },
  { id: 'IPC5', especieAnimal: ['Conejo'], nombreInstinto: 'Reproducción Estacional', funcionNatural: 'Ciclos reproductivos naturales', manifestacionSana: 'Comportamientos estacionales normales', distorsionDomestica: 'Comportamientos reproductivos problemáticos', preguntaTesteo: '¿Los ciclos reproductivos están alterados?', fuenteManual: "P.5" },

  // CABALLOS (Adaptado de principios generales y conocimientos comunes, no explícito en P.3-5)
  { id: 'IPH1', especieAnimal: ['Caballo'], nombreInstinto: 'Instinto de Huida', funcionNatural: 'Respuesta rápida a amenazas percibidas', manifestacionSana: 'Alerta apropiada, evaluación rápida, huida si es necesario', distorsionDomestica: 'Pánico extremo, reacciones exageradas, "spooking" constante', preguntaTesteo: '¿El instinto de huida está desequilibrado (exagerado o ausente)?', fuenteManual: "General" },
  { id: 'IPH2', especieAnimal: ['Caballo'], nombreInstinto: 'Vida de Manada (Jerarquía)', funcionNatural: 'Establecer y respetar estructura social dentro del grupo', manifestacionSana: 'Interacciones sociales pacíficas, roles claros, liderazgo y seguimiento', distorsionDomestica: 'Agresividad excesiva, aislamiento, sumisión extrema, falta de respeto por el espacio personal', preguntaTesteo: '¿Hay problemas con la jerarquía o comportamiento social en la manada?', fuenteManual: "General" },
  { id: 'IPH3', especieAnimal: ['Caballo'], nombreInstinto: 'Pastoreo Continuo', funcionNatural: 'Consumo frecuente de pequeñas cantidades de forraje', manifestacionSana: 'Patrones de alimentación naturales, salud digestiva óptima', distorsionDomestica: 'Problemas digestivos (cólicos), vicios de establo (cribbing, tragar aire), obesidad o bajo peso', preguntaTesteo: '¿Los patrones de alimentación son naturales y adecuados?', fuenteManual: "General" },
  { id: 'IPH4', especieAnimal: ['Caballo'], nombreInstinto: 'Movimiento y Exploración', funcionNatural: 'Necesidad de recorrer distancias, explorar entorno', manifestacionSana: 'Curiosidad, buen tono muscular, comportamiento activo', distorsionDomestica: 'Apatía, vicios de establo por aburrimiento, problemas musculares o articulares por falta de movimiento', preguntaTesteo: '¿Tiene suficiente oportunidad para movimiento libre y exploración?', fuenteManual: "General" },
  { id: 'IPH5', especieAnimal: ['Caballo'], nombreInstinto: 'Comunicación Sutil', funcionNatural: 'Uso de lenguaje corporal complejo para comunicarse', manifestacionSana: 'Señales claras y entendidas por otros caballos y humanos atentos', distorsionDomestica: 'Malentendidos, comportamiento "impredecible" (señales no leídas), frustración', preguntaTesteo: '¿Su comunicación es clara y se le permite expresarse?', fuenteManual: "General" },
];

export const CAUSAS_BLOQUEO_INSTINTO_DATA: CausaBloqueo[] = [
  // Adaptado de conocimientos generales, ya que el manual P.5 describe "Señales de Instintos Bloqueados" y no "Causas"
  { id: 'CB1', causa: 'Entorno Inadecuado/Restrictivo', descripcionDetallada: 'Falta de espacio, recursos o estímulos para expresar el instinto.', preguntaConfirmacion: '¿El entorno físico o social limita este instinto?' },
  { id: 'CB2', causa: 'Manejo Humano Inapropiado', descripcionDetallada: 'Sobreprotección, castigo por expresión natural, humanización, falta de comprensión de las necesidades de la especie.', preguntaConfirmacion: '¿Las acciones o expectativas humanas bloquean este instinto?' },
  { id: 'CB3', causa: 'Experiencia Traumática Pasada', descripcionDetallada: 'Un evento negativo asociado con la expresión del instinto.', preguntaConfirmacion: '¿Un trauma previo (conocido o sospechado) inhibe este instinto?' },
  { id: 'CB4', causa: 'Falta de Aprendizaje/Socialización Temprana', descripcionDetallada: 'No tuvo oportunidad de aprender o practicar el comportamiento en etapas críticas.', preguntaConfirmacion: '¿Hubo deficiencias en su desarrollo temprano que afecten este instinto?' },
  { id: 'CB5', causa: 'Dolor o Malestar Físico', descripcionDetallada: 'Una condición médica subyacente que impide o hace dolorosa la expresión del instinto.', preguntaConfirmacion: '¿Un problema de salud podría estar interfiriendo con este instinto?' },
  { id: 'CB6', causa: 'Estrés Crónico o Ansiedad', descripcionDetallada: 'Un estado general de estrés o miedo que suprime comportamientos naturales.', preguntaConfirmacion: '¿El estrés generalizado está afectando la expresión de este instinto?' },
  { id: 'CB7', causa: 'Ausencia de Desencadenantes Apropiados', descripcionDetallada: 'Falta del estímulo correcto que normalmente activaría el instinto.', preguntaConfirmacion: '¿Faltan los estímulos necesarios para que este instinto se manifieste?' },
];

// --- DATOS PARA DIAGNÓSTICO DE CONFLICTO CON EL DUEÑO (Manual V4.0, P.9) ---
export const CONFLICTOS_CON_DUENO_DATA: Conflicto[] = [
  { id: 'CD1', tipo: 'Absorción de Trauma (Dueño)', pregunta: '¿El animal está absorbiendo traumas del dueño?', efectoEnInstintos: 'Bloquea instintos de supervivencia', activo: false, intensidad: 0, fuenteManual: "P.9" },
  { id: 'CD2', tipo: 'Reflejo de Ansiedad (Dueño)', pregunta: '¿El animal refleja la ansiedad del dueño?', efectoEnInstintos: 'Hiperactivación de vigilancia', activo: false, intensidad: 0, fuenteManual: "P.9" },
  { id: 'CD3', tipo: 'Sobreprotección (Dueño)', pregunta: '¿El animal sufre por sobreprotección del dueño?', efectoEnInstintos: 'Bloquea exploración y autonomía', activo: false, intensidad: 0, fuenteManual: "P.9" },
  { id: 'CD4', tipo: 'Abandono Emocional (Dueño)', pregunta: '¿El animal siente abandono emocional del dueño?', efectoEnInstintos: 'Hiperactivación de apego', activo: false, intensidad: 0, fuenteManual: "P.9" },
  { id: 'CD5', tipo: 'Conflicto de Roles (Animal-Humano)', pregunta: '¿Hay confusión en los roles animal-humano?', efectoEnInstintos: 'Bloquea TODOS los instintos', activo: false, intensidad: 0, fuenteManual: "P.9" },
  { id: 'CD6', tipo: 'Energía Depresiva (Dueño)', pregunta: '¿El animal absorbe depresión del dueño?', efectoEnInstintos: 'Suprime vitalidad natural', activo: false, intensidad: 0, fuenteManual: "P.9" },
  { id: 'CD7', tipo: 'Culpa del Dueño', pregunta: '¿El animal carga con la culpa del dueño?', efectoEnInstintos: 'Bloquea expresión natural', activo: false, intensidad: 0, fuenteManual: "P.9" },
];

// --- DATOS PARA INFLUENCIA DEL LUGAR (Manual V4.0, P.10) ---
export const MEMORIAS_LUGAR_DATA: MemoriaLugar[] = [
    { id: 'ML1', memoria: 'Muerte/Duelo', efectoEnInstintos: 'Suprime vitalidad, instintos de juego', pregunta: '¿La memoria de muerte del lugar afecta al animal?', activo: false, intensidad: 0, fuenteManual: "P.10"},
    { id: 'ML2', memoria: 'Violencia', efectoEnInstintos: 'Hiperactivación protectora, miedo', pregunta: '¿La memoria de violencia afecta al animal?', activo: false, intensidad: 0, fuenteManual: "P.10"},
    { id: 'ML3', memoria: 'Abandono', efectoEnInstintos: 'Ansiedad de separación, apego excesivo', pregunta: '¿La memoria de abandono afecta al animal?', activo: false, intensidad: 0, fuenteManual: "P.10"},
    { id: 'ML4', memoria: 'Conflictos', efectoEnInstintos: 'Estrés territorial, agresividad', pregunta: '¿Los conflictos del lugar afectan al animal?', activo: false, intensidad: 0, fuenteManual: "P.10"},
    { id: 'ML5', memoria: 'Enfermedad', efectoEnInstintos: 'Suprime sistema inmune, vitalidad', pregunta: '¿La memoria de enfermedad afecta al animal?', activo: false, intensidad: 0, fuenteManual: "P.10"},
    { id: 'ML6', memoria: 'Miedo/Terror', efectoEnInstintos: 'Bloquea exploración, confianza', pregunta: '¿La memoria de terror afecta al animal?', activo: false, intensidad: 0, fuenteManual: "P.10"},
];

export const ZONAS_HOGAR_DATA: ZonaHogar[] = [
    // Generalizado, no en manual P.10
    { id: 'ZH1', nombre: 'Dormitorio principal', memoriasAsociadas: 'Intimidad, descanso, vulnerabilidad'},
    { id: 'ZH2', nombre: 'Sala de estar / Área común', memoriasAsociadas: 'Convivencia, tensiones familiares, rutinas'},
    { id: 'ZH3', nombre: 'Cocina / Comedor', memoriasAsociadas: 'Alimentación, nutrición, ansiedad por comida'},
    { id: 'ZH4', nombre: 'Jardín / Patio / Exterior', memoriasAsociadas: 'Libertad, territorialidad, amenazas externas'},
    { id: 'ZH5', nombre: 'Entrada / Puerta Principal', memoriasAsociadas: 'Llegadas, partidas, protección del territorio'},
    { id: 'ZH6', nombre: 'Lugar de descanso del animal', memoriasAsociadas: 'Seguridad personal, refugio, vulnerabilidad'},
    { id: 'ZH7', nombre: 'Pasillos / Escaleras', memoriasAsociadas: 'Transición, conexión/separación de espacios'},
];

// --- DATOS PARA EVALUACIÓN DE NECESIDADES BIOLÓGICAS (General, no explícito en Manual P.10) ---
export const NECESIDADES_BIOLOGICAS_DATA: NecesidadBiologica[] = [
    // Perro
    { id: 'NBD1', especieAnimal: ['Perro'], necesidad: 'Ejercicio físico adecuado a raza y edad', preguntaEvaluacion: '¿Recibe suficiente ejercicio físico diario?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBD2', especieAnimal: ['Perro'], necesidad: 'Estimulación mental y enriquecimiento ambiental', preguntaEvaluacion: '¿Tiene juguetes, entrenamiento, desafíos mentales?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBD3', especieAnimal: ['Perro'], necesidad: 'Socialización regular (con perros y humanos)', preguntaEvaluacion: '¿Tiene interacciones sociales positivas y regulares?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBD4', especieAnimal: ['Perro'], necesidad: 'Dieta balanceada y apropiada', preguntaEvaluacion: '¿Su alimentación es adecuada y de calidad?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBD5', especieAnimal: ['Perro'], necesidad: 'Espacio seguro y confortable para descansar', preguntaEvaluacion: '¿Dispone de un lugar propio, seguro y cómodo?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBD6', especieAnimal: ['Perro'], necesidad: 'Higiene y cuidados veterinarios regulares', preguntaEvaluacion: '¿Recibe atención veterinaria y de higiene adecuada?', satisfecha: true, intensidadNoSatisfecha: 0 },
    // Gato
    { id: 'NBG1', especieAnimal: ['Gato'], necesidad: 'Oportunidades para trepar y observar desde alturas', preguntaEvaluacion: '¿Tiene acceso a espacios verticales seguros?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBG2', especieAnimal: ['Gato'], necesidad: 'Estimulación de instintos de caza (juego)', preguntaEvaluacion: '¿Participa en juegos que simulan la caza?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBG3', especieAnimal: ['Gato'], necesidad: 'Rascadores adecuados y disponibles', preguntaEvaluacion: '¿Tiene dónde afilar sus uñas apropiadamente?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBG4', especieAnimal: ['Gato'], necesidad: 'Control sobre su entorno y rutinas predecibles', preguntaEvaluacion: '¿Se respetan sus rutinas y tiene control sobre su espacio?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBG5', especieAnimal: ['Gato'], necesidad: 'Múltiples recursos (bandejas de arena, comederos, bebederos)', preguntaEvaluacion: '¿Tiene suficientes recursos, especialmente si hay más gatos?', satisfecha: true, intensidadNoSatisfecha: 0 },
    // Ave
    { id: 'NBA1', especieAnimal: ['Ave'], necesidad: 'Jaula o aviario espacioso y seguro', preguntaEvaluacion: '¿Su hábitat es suficientemente grande y seguro?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBA2', especieAnimal: ['Ave'], necesidad: 'Oportunidades de vuelo o ejercicio fuera de la jaula', preguntaEvaluacion: '¿Tiene tiempo seguro para volar o ejercitarse?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBA3', especieAnimal: ['Ave'], necesidad: 'Enriquecimiento ambiental (juguetes, forrajeo)', preguntaEvaluacion: '¿Tiene estímulos para forrajear y jugar?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBA4', especieAnimal: ['Ave'], necesidad: 'Interacción social (con su especie o humanos, según especie)', preguntaEvaluacion: '¿Recibe la interacción social que necesita?', satisfecha: true, intensidadNoSatisfecha: 0 },
    // Conejo
    { id: 'NBC1', especieAnimal: ['Conejo'], necesidad: 'Espacio amplio para moverse, saltar y explorar', preguntaEvaluacion: '¿Tiene suficiente espacio para comportarse naturalmente?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBC2', especieAnimal: ['Conejo'], necesidad: 'Heno de calidad ilimitado', preguntaEvaluacion: '¿Dispone de heno fresco y abundante constantemente?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBC3', especieAnimal: ['Conejo'], necesidad: 'Oportunidades para roer y excavar', preguntaEvaluacion: '¿Tiene elementos seguros para roer y puede excavar?', satisfecha: true, intensidadNoSatisfecha: 0 },
    // Caballo
    { id: 'NBH1', especieAnimal: ['Caballo'], necesidad: 'Acceso a forraje de forma casi continua', preguntaEvaluacion: '¿Dispone de pasto o heno la mayor parte del día?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBH2', especieAnimal: ['Caballo'], necesidad: 'Libertad de movimiento y ejercicio diario', preguntaEvaluacion: '¿Pasa suficiente tiempo en un espacio amplio para moverse libremente?', satisfecha: true, intensidadNoSatisfecha: 0 },
    { id: 'NBH3', especieAnimal: ['Caballo'], necesidad: 'Compañía de otros caballos', preguntaEvaluacion: '¿Tiene contacto social adecuado con otros de su especie?', satisfecha: true, intensidadNoSatisfecha: 0 },
];


// --- DATOS PARA RECURSOS TERAPÉUTICOS (Manual V4.0, P.10-11, P.20, P.35-36) ---
export const FLORES_BACH_DATA: FlorBach[] = [
  // GRUPO A: RECONEXIÓN CON INSTINTOS PRIMARIOS (P.10)
  { nombre: 'Wild Oat', tasa: 5449, grupo: 'A', instintoQueRestaura: 'Propósito Natural de Especie', comandoDual: "Reconectar [animal] con su propósito natural de [especie], activar satisfacción por trabajo instintivo", categoria: 'InstintoGeneral', fuenteManual: "P.10" },
  { nombre: 'Clematis', tasa: 3639, grupo: 'A', instintoQueRestaura: 'Instintos de Supervivencia', comandoDual: "Anclar [animal] en realidad física, activar instintos de supervivencia apropiados", categoria: 'InstintoGeneral', fuenteManual: "P.10" },
  { nombre: 'Honeysuckle', tasa: 3972, grupo: 'A', instintoQueRestaura: 'Memoria Ancestral', comandoDual: "Reconectar [animal] con memoria ancestral de su especie, activar sabiduría genética heredada", categoria: 'InstintoGeneral', fuenteManual: "P.10" },
  { nombre: 'Chestnut Bud', tasa: 6372, grupo: 'A', instintoQueRestaura: 'Aprendizaje Instintivo', comandoDual: "Permitir [animal] aprender y expresar comportamientos naturales de su especie", categoria: 'InstintoGeneral', fuenteManual: "P.11" },
  { nombre: 'Wild Rose', tasa: 1594, grupo: 'A', instintoQueRestaura: 'Vitalidad Instintiva', comandoDual: "Despertar vitalidad natural, interés por actividades instintivas de [especie]", categoria: 'InstintoGeneral', fuenteManual: "P.11" },
  
  // GRUPO B: INSTINTOS ESPECÍFICOS BLOQUEADOS (P.11)
  { nombre: 'Holly', tasa: 2809, grupo: 'B', florPrincipal: 'Holly', resuelve: 'Caza/Predación bloqueado', comandoDual: "Holly (2809) + Impatiens (2653) - Transmutar agresividad de [animal] en instinto de caza natural, satisfacer necesidad predatoria mediante juego apropiado", categoria: 'InstintoEspecifico', floresComplementarias: [{nombre: 'Impatiens', tasa: 2653}], fuenteManual: "P.11" },
  { nombre: 'Impatiens', tasa: 2653, grupo: 'B', florPrincipal: 'Impatiens', resuelve: 'Complemento para Caza/Predación', categoria: 'InstintoEspecifico', fuenteManual: "P.11" }, 
  { nombre: 'Vine', tasa: 3317, grupo: 'B', florPrincipal: 'Vine', resuelve: 'Territorio bloqueado', comandoDual: "Vine (3317) + Beech (1436) - Equilibrar territorialidad de [animal], expresar protección sin agresividad excesiva", categoria: 'InstintoEspecifico', floresComplementarias: [{nombre: 'Beech', tasa: 1436}], fuenteManual: "P.11" },
  { nombre: 'Beech', tasa: 1436, grupo: 'B', florPrincipal: 'Beech', resuelve: 'Complemento para Territorio', categoria: 'InstintoEspecifico', fuenteManual: "P.11" },
  { nombre: 'Centaury', tasa: 2135, grupo: 'B', florPrincipal: 'Centaury', resuelve: 'Jerarquía bloqueada', comandoDual: "Centaury (2135) + Water Violet (1579) - Equilibrar jerarquía natural de [animal], expresar liderazgo o seguimiento apropiado", categoria: 'InstintoEspecifico', floresComplementarias: [{nombre: 'Water Violet', tasa: 1579}], fuenteManual: "P.11" },
  { nombre: 'Water Violet', tasa: 1579, grupo: 'B', florPrincipal: 'Water Violet', resuelve: 'Complemento para Jerarquía', categoria: 'InstintoEspecifico', fuenteManual: "P.11" },
  { nombre: 'Agrimony', tasa: 2247, grupo: 'B', florPrincipal: 'Agrimony', resuelve: 'Comunicación bloqueada', comandoDual: "Agrimony (2247) + Heather (6338) - Permitir [animal] expresar necesidades auténticamente, comunicación clara sin demanda excesiva", categoria: 'InstintoEspecifico', floresComplementarias: [{nombre: 'Heather', tasa: 6338}], fuenteManual: "P.11" },
  { nombre: 'Heather', tasa: 6338, grupo: 'B', florPrincipal: 'Heather', resuelve: 'Complemento para Comunicación', categoria: 'InstintoEspecifico', fuenteManual: "P.11" },
  { nombre: 'Mimulus', tasa: 5733, grupo: 'B', florPrincipal: 'Mimulus', resuelve: 'Exploración bloqueada', comandoDual: "Mimulus (5733) + Larch (3363) - Desarrollar confianza de [animal] en exploración, valentía natural para conocer territorio", categoria: 'InstintoEspecifico', floresComplementarias: [{nombre: 'Larch', tasa: 3363}], fuenteManual: "P.11" },
  { nombre: 'Larch', tasa: 3363, grupo: 'B', florPrincipal: 'Larch', resuelve: 'Complemento para Exploración', categoria: 'InstintoEspecifico', fuenteManual: "P.11" },
  { nombre: 'Chicory', tasa: 1622, grupo: 'B', florPrincipal: 'Chicory', resuelve: 'Independencia bloqueada', comandoDual: "Chicory (1622) + Walnut (2803) - Equilibrar independencia de [animal] con vínculos sanos, autosuficiencia sin aislamiento", categoria: 'InstintoEspecifico', floresComplementarias: [{nombre: 'Walnut', tasa: 2803}], fuenteManual: "P.11" },
  { nombre: 'Walnut', tasa: 2803, grupo: 'B', florPrincipal: 'Walnut', resuelve: 'Complemento para Independencia', categoria: 'InstintoEspecifico', fuenteManual: "P.11" },

  // FLORES DE BACH ESPECIALIZADAS PARA TRAUMA ANIMAL (P.20, Anexo A2 P.35-36)
  { nombre: 'Star of Bethlehem', tasa: 3672, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Violencia Física', efectoPrincipal: "Sanar shock de violencia, restaurar autocontrol y seguridad básica", floresComplementarias: [{nombre: 'Rock Rose', tasa: 2841}, {nombre: 'Cherry Plum', tasa: 1573}], fuenteManual: "P.20, P.35" },
  { nombre: 'Honeysuckle', tasa: 3972, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Abandono Repetido', efectoPrincipal: "Sanar duelo por pérdidas múltiples, restaurar capacidad de vincularse", floresComplementarias: [{nombre: 'Sweet Chestnut', tasa: 2805}, {nombre: 'Wild Rose', tasa: 1594}], fuenteManual: "P.20, P.36" },
  { nombre: 'Olive', tasa: 4122, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Negligencia Severa', efectoPrincipal: "Restaurar vitalidad tras privación, liberar autoculpa por supervivencia", floresComplementarias: [{nombre: 'Pine', tasa: 1257}, {nombre: 'Larch', tasa: 3363}], fuenteManual: "P.20, P.36" },
  { nombre: 'Crab Apple', tasa: 1214, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Abuso Sexual', efectoPrincipal: "Limpiar trauma sexual, restaurar pureza e inocencia natural", floresComplementarias: [{nombre: 'Star of Bethlehem', tasa: 3672}, {nombre: 'Pine', tasa: 1257}], fuenteManual: "P.20, P.36" },
  { nombre: 'Sweet Chestnut', tasa: 2805, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Tortura/Crueldad', efectoPrincipal: "Sanar desesperanza extrema, restaurar fe en bondad de la vida", floresComplementarias: [{nombre: 'Star of Bethlehem', tasa: 3672}, {nombre: 'Oak', tasa: 5847}], fuenteManual: "P.20" },
  { nombre: 'Aspen', tasa: 4178, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Encierro Prolongado', efectoPrincipal: "Liberar claustrofobia y ansiedad, restaurar conexión con libertad", floresComplementarias: [{nombre: 'Clematis', tasa: 3639}, {nombre: 'Impatiens', tasa: 2653}], fuenteManual: "P.21, P.36" },
  { nombre: 'Chicory', tasa: 1622, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Separación Traumática', efectoPrincipal: "Sanar pérdida de figuras de apego, equilibrar necesidad de conexión", floresComplementarias: [{nombre: 'Red Chestnut', tasa: 5719}, {nombre: 'Honeysuckle', tasa: 3972}], fuenteManual: "P.21, P.36" },
  { nombre: 'Water Violet', tasa: 1579, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Humillación Pública', efectoPrincipal: "Restaurar dignidad natural, sanar vergüenza internalizada", floresComplementarias: [{nombre: 'Larch', tasa: 3363}, {nombre: 'Crab Apple', tasa: 1214}], fuenteManual: "P.21" }, // Nota: Tasa Water Violet es 1579, el manual indica Water Violet.
  { nombre: 'Gorse', tasa: 2627, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Sobrevivencia Extrema', efectoPrincipal: "Restaurar esperanza y alegría de vivir, superar desesperanza aprendida", floresComplementarias: [{nombre: 'Wild Rose', tasa: 1594}, {nombre: 'Olive', tasa: 4122}], fuenteManual: "P.21, P.36" }, // Tasa de Gorse es 2627, no 262 del manual.
  { nombre: 'Pine', tasa: 1257, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Condicionamiento Brutal', efectoPrincipal: "Liberar programación de culpa, reaprender patrones naturales", floresComplementarias: [{nombre: 'Chestnut Bud', tasa: 6372}, {nombre: 'Walnut', tasa: 2803}], fuenteManual: "P.21, P.36" },
  { nombre: 'Rock Rose', tasa: 2841, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Terror extremo', efectoPrincipal: "Para terror paralizante, pánico agudo.", fuenteManual: "General"},
  { nombre: 'Cherry Plum', tasa: 1573, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Pérdida de control', efectoPrincipal: "Miedo a perder el control, comportamientos explosivos.", fuenteManual: "General"},
  { nombre: 'Oak', tasa: 5847, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Agotamiento por lucha', efectoPrincipal: "Para el luchador que no se rinde pero está exhausto.", fuenteManual: "General"},
  { nombre: 'Rescue Remedy', tasa: 476362, grupo: 'TraumaGeneral', tipoTraumaAsociado: 'Emergencia General', efectoPrincipal: "Combinación para shock, trauma agudo, emergencias.", fuenteManual: "General"},

];

// --- DATOS PARA COMANDOS RADIÓNICOS ESPECÍFICOS (Manual V4.0, P.12, P.15-23, P.32, P.37) ---
export const COMANDOS_ESPECIFICOS_DATA: ComandoEspecifico[] = [
  // RECONEXIÓN DE MANADA (PERROS) (P.12)
  { id: 'CMD_P_RM_1', comando: "Reconectar [nombre] con instintos de manada, establecer jerarquía clara y respetuosa en familia humana", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'PerrosManada', fuenteManual: "P.12", especie: "Perro" },
  { id: 'CMD_P_RM_2', comando: "Activar confianza de [nombre] en liderazgo humano apropiado, seguridad en estructura social", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'PerrosManada', fuenteManual: "P.12", especie: "Perro" },
  { id: 'CMD_P_RM_3', comando: "Permitir [nombre] expresar protección natural sin agresividad excesiva", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'PerrosManada', fuenteManual: "P.12", especie: "Perro" },
  // CAZA Y TRABAJO (PERROS) (P.12)
  { id: 'CMD_P_CT_1', comando: "Satisfacer instinto de caza de [nombre] mediante juego constructivo y búsqueda", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'PerrosCazaTrabajo', fuenteManual: "P.12", especie: "Perro" },
  { id: 'CMD_P_CT_2', comando: "Activar propósito de trabajo en [nombre], satisfacción por tareas apropiadas", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'PerrosCazaTrabajo', fuenteManual: "P.12", especie: "Perro" },
  { id: 'CMD_P_CT_3', comando: "Transmutar energía destructiva de [nombre] en actividades constructivas de especie", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'PerrosCazaTrabajo', fuenteManual: "P.12", especie: "Perro" },
  // INDEPENDENCIA FELINA (GATOS) (P.12)
  { id: 'CMD_G_IF_1', comando: "Honrar independencia natural de [nombre], equilibrio entre afecto y soledad", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'GatosIndependencia', fuenteManual: "P.12", especie: "Gato" },
  { id: 'CMD_G_IF_2', comando: "Permitir [nombre] controlar interacciones sociales según necesidad felina", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'GatosIndependencia', fuenteManual: "P.12", especie: "Gato" },
  { id: 'CMD_G_IF_3', comando: "Desarrollar autosuficiencia de [nombre] sin aislamiento total", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'GatosIndependencia', fuenteManual: "P.12", especie: "Gato" },
  // CAZA SOLITARIA (GATOS) (P.12)
  { id: 'CMD_G_CS_1', comando: "Satisfacer instinto cazador de [nombre] mediante juego de acecho apropiado", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'GatosCaza', fuenteManual: "P.12", especie: "Gato" },
  { id: 'CMD_G_CS_2', comando: "Activar secuencias naturales de caza: acechar-saltar-capturar en [nombre]", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'GatosCaza', fuenteManual: "P.12", especie: "Gato" },
  { id: 'CMD_G_CS_3', comando: "Transmutar agresividad de [nombre] en expresión natural de caza", categoriaGeneral: 'ReconexionInstintiva', subCategoria: 'GatosCaza', fuenteManual: "P.12", especie: "Gato" },

  // PROTOCOLOS INTENSIVOS DE LIBERACIÓN TRAUMÁTICA (P.15-19)
  // FASE 1: ESTABILIZACIÓN DE EMERGENCIA (PERRO GOLPEADO) (P.15-16)
  { id: 'CMD_TFS_PG_F1_MAIN', comando: "\"Rescue Remedy (476362) + Rock Rose (2841) + Star of Bethlehem (3672) + Sweet Chestnut (2805) - EMERGENCY: Detener cascada traumática en [nombre], estabilizar sistema nervioso tras agresión física, neutralizar terror extremo y desesperanza, activar mecanismos básicos de supervivencia segura, crear burbuja energética de protección inmediata\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Estabilizacion', tipoTraumaAsociado: 'TraumaFísicoSevero', especie: 'Perro', fuenteManual: "P.16", duracionSugerida: "5-7 días" },
  { id: 'CMD_TFS_PG_F1_COMP', comando: "\"Proteger [nombre] de re-traumatización, sostener sistema durante shock post-rescate, facilitar transición de supervivencia a seguridad básica, restaurar conexión mínima con voluntad de vivir\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Estabilizacion', tipoTraumaAsociado: 'TraumaFísicoSevero', especie: 'Perro', fuenteManual: "P.16", duracionSugerida: "5-7 días" },
  // FASE 2: DESACTIVACIÓN MEMORIAS TRAUMÁTICAS (PERRO GOLPEADO - GOLPES/AGRESIÓN FÍSICA) (P.16-17)
  { id: 'CMD_TFS_PG_F2_MAIN', comando: "\"Star of Bethlehem (3672) + Honeysuckle (3972) + Cherry Plum (1573) + Pine (1257) - Sanar memoria celular de golpes y agresión física en [nombre], neutralizar terror automático ante movimientos humanos rápidos, liberar culpa internalizada por maltrato recibido, desactivar respuestas de pánico ante objetos/sonidos asociados, restaurar capacidad de distinguir humanos seguros de amenazas\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Desactivacion', tipoTraumaAsociado: 'GolpesAgresionFisica', especie: 'Perro', fuenteManual: "P.17", duracionSugerida: "14-21 días" },
  { id: 'CMD_TFS_PG_F2_RECON', comando: "\"Instalar nueva memoria de seguridad física, reemplazar expectativa de dolor con expectativa de cuidado, permitir [nombre] recibir caricias sin terror, restaurar confianza en acercamiento humano gentil\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Desactivacion', tipoTraumaAsociado: 'GolpesAgresionFisica', especie: 'Perro', fuenteManual: "P.17", duracionSugerida: "14-21 días" },
  // FASE 2: LIBERACIÓN ESPECÍFICA TRAUMA EQUINO (CABALLO MALTRATADO CON LÁTIGO) (P.17)
  { id: 'CMD_TFS_CE_F2_MAIN', comando: "\"Star of Bethlehem (3672) + Mimulus (5733) + Larch (3363) + Water Violet (1579) - Sanar memoria de látigo y trabajo forzado en [nombre], neutralizar pánico ante cuerdas, correas y herramientas, liberar terror grabado en memoria muscular, restaurar dignidad equina después de humillación, sanar heridas emocionales de dominación brutal\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Desactivacion', tipoTraumaAsociado: 'MaltratoConLatigo', especie: 'Caballo', fuenteManual: "P.17", duracionSugerida: "14-21 días (implicito)"},
  { id: 'CMD_TFS_CE_F2_REST', comando: "\"Reconectar [nombre] con orgullo de ser caballo, restaurar espíritu libre dentro de colaboración voluntaria, permitir partnership humano-equino basado en respeto mutuo, sanar trauma de sometimiento mediante nueva experiencia de cooperación\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Desactivacion', tipoTraumaAsociado: 'MaltratoConLatigo', especie: 'Caballo', fuenteManual: "P.18", duracionSugerida: "21 días"},
  // FASE 3: RECONEXIÓN CON INSTINTOS NATURALES (UNIVERSAL POST-TRAUMA) (P.18)
  { id: 'CMD_TFS_ALL_F3_MAIN', comando: "\"Wild Oat (5449) + Honeysuckle (3972) + Larch (3363) + Olive (4122) - Reconectar [nombre] con identidad natural de [especie] después de experiencia de deshumanización/maltrato, reactivar instintos saludables que fueron suprimidos por supervivencia, restaurar confianza en capacidades naturales, despertar alegría de expresar naturaleza auténtica sin miedo\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Reconexion', tipoTraumaAsociado: 'UniversalPostTrauma', especie: 'Universal', fuenteManual: "P.18", duracionSugerida: "21-28 días"},
  { id: 'CMD_TFS_P_F3_ESP', comando: "\"PERROS: Restaurar confianza en jerarquía amorosa, reconectar con alegría del juego y trabajo cooperativo, permitir expresión de lealtad sin sumisión patológica\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Reconexion', tipoTraumaAsociado: 'UniversalPostTrauma', especie: 'Perro', fuenteManual: "P.18"},
  { id: 'CMD_TFS_H_F3_ESP', comando: "\"CABALLOS: Restaurar partnership noble con humanos, reconectar con poder y gracia natural, equilibrar fuerza con gentileza en interacción\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Reconexion', tipoTraumaAsociado: 'UniversalPostTrauma', especie: 'Caballo', fuenteManual: "P.19"},
  { id: 'CMD_TFS_G_F3_ESP', comando: "\"GATOS: Restaurar dignidad e independencia felina, reconectar con confianza en capacidades de supervivencia, equilibrar autonomía con capacidad de recibir amor\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Reconexion', tipoTraumaAsociado: 'UniversalPostTrauma', especie: 'Gato', fuenteManual: "P.19"},
  // FASE 4: INTEGRACIÓN EN NUEVA VIDA (UNIVERSAL POST-TRAUMA) (P.19)
  { id: 'CMD_TFS_ALL_F4_MAIN', comando: "\"Walnut (2803) + Chestnut Bud (6372) + Gentian (4156) + Oak (5847) - Integrar [nombre] nueva identidad post-sanación en vida presente, consolidar aprendizajes de seguridad y confianza, establecer patrones sanos de interacción con nueva familia, equilibrar memoria del pasado con expectativas positivas del futuro\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Integracion', tipoTraumaAsociado: 'UniversalPostTrauma', especie: 'Universal', fuenteManual: "P.19", duracionSugerida: "14-21 días"},
  { id: 'CMD_TFS_ALL_F4_SEAL', comando: "\"Sellar sanación de trauma en [nombre], proteger de regresiones durante momentos de estrés, mantener acceso a recursos internos desarrollados durante recuperación, permitir crecimiento continuo desde fundación de seguridad establecida\"", categoriaGeneral: 'TraumaFaseProtocolo', faseProtocoloTrauma: 'Integracion', tipoTraumaAsociado: 'UniversalPostTrauma', especie: 'Universal', fuenteManual: "P.19-20", duracionSugerida: "14-21 días"},

  // COMANDOS ESPECÍFICOS POR EXPERIENCIA TRAUMÁTICA (P.21-23)
  { id: 'CMD_EXP_PELEAS', comando: "\"Holly (2809) + Star of Bethlehem (3672) + Pine (1257) + Wild Oat (5449) - Transmutar agresividad condicionada de [nombre] en protección natural, sanar trauma de ser forzado a lastimar otros animales, liberar culpa por actos violentos forzados, reconectar con naturaleza cooperativa natural del perro, permitir socialización pacífica con otros perros, restaurar capacidad de juego sin agresividad\"", categoriaGeneral: 'TraumaComandoEspecificoTipo', tipoTraumaAsociado: 'PerrosPeleas', especie: 'Perro', fuenteManual: "P.21"},
  { id: 'CMD_EXP_CARRERAS', comando: "\"Oak (5847) + Star of Bethlehem (3672) + Olive (4122) + Elm (7884) - Sanar [nombre] de presión extrema por rendimiento, liberar trauma de ser forzado a continuar con dolor, restaurar amor natural por correr sin presión externa, sanar agotamiento físico y emocional por sobreexigencia, reconectar con alegría del movimiento libre, equilibrar fuerza natural con derecho al descanso\"", categoriaGeneral: 'TraumaComandoEspecificoTipo', tipoTraumaAsociado: 'CaballosCarrerasAbusados', especie: 'Caballo', fuenteManual: "P.22"},
  { id: 'CMD_EXP_ACUMULADORES', comando: "\"Water Violet (1579) + Crab Apple (1214) + Mimulus (5733) + Clematis (3639) - Restaurar dignidad felina de [nombre] tras hacinamiento, sanar trauma de pérdida de territorio individual, limpiar memoria de suciedad y enfermedad, superar miedo a competencia por recursos, reconectar con independencia y territorialidad sana, permitir disfrute de limpieza y espacios ordenados\"", categoriaGeneral: 'TraumaComandoEspecificoTipo', tipoTraumaAsociado: 'GatosAcumuladores', especie: 'Gato', fuenteManual: "P.22"},
  { id: 'CMD_EXP_LABORATORIO', comando: "\"Sweet Chestnut (2805) + Star of Bethlehem (3672) + Walnut (2803) + Wild Oat (5449) - Sanar [nombre] de trauma médico y manipulación forzada, neutralizar terror asociado con humanos en batas blancas, liberar memoria de procedimientos invasivos y dolor, reconectar con propósito natural de [especie] más allá de uso humano, restaurar confianza en autonomía corporal, permitir experiencia de vida sin dolor constante\"", categoriaGeneral: 'TraumaComandoEspecificoTipo', tipoTraumaAsociado: 'AnimalesLaboratorio', especie: 'Universal', fuenteManual: "P.22-23"},
  { id: 'CMD_EXP_SEPARACIONTM', comando: "\"Chicory (1622) + Star of Bethlehem (3672) + Red Chestnut (5719) + Honeysuckle (3972) - Sanar [nombre] trauma de separación prematura de madre, neutralizar terror de abandono grabado en primeras semanas, liberar ansiedad extrema por supervivencia, crear sensación de seguridad maternal en nuevos cuidadores, permitir desarrollo de confianza básica en el mundo, facilitar transición de supervivencia a crecimiento sano\"", categoriaGeneral: 'TraumaComandoEspecificoTipo', tipoTraumaAsociado: 'CachorrosCriasSeparacionTraumatica', especie: 'Universal', duracionSugerida: "28-35 días (trauma fundacional)", fuenteManual: "P.23"},
  { id: 'CMD_EXP_CAUTIVERIOB', comando: "\"Wild Oat (5449) + Clematis (3639) + Chestnut Bud (6372) + Gentian (4156) - Despertar [nombre] a posibilidades de vida más allá de supervivencia, activar memoria genética de comportamientos naturales nunca expresados, facilitar aprendizaje de patrones naturales de [especie], superar desesperanza aprendida de generaciones en cautiverio, conectar con alegría y propósito natural a pesar de historia familiar\"", categoriaGeneral: 'TraumaComandoEspecificoTipo', tipoTraumaAsociado: 'AnimalesNacidosCautiverioBrutal', especie: 'Universal', fuenteManual: "P.23"},

  // PROTOCOLOS DE EMERGENCIA DURANTE RECUPERACIÓN (P.32, P.37 Anexo A4)
  { id: 'CMD_EMER_REGRESIONA', comando: "\"Rescue Remedy (476362) + Star of Bethlehem (3672) - EMERGENCY: Sostener [nombre] durante regresión traumática, restaurar progreso alcanzado, reactivar recursos de sanación desarrollados, evitar retraumatización durante proceso natural de integración\"", categoriaGeneral: 'TraumaEmergenciaRecuperacion', tipoTraumaAsociado: 'RegresionTraumaticaAguda', especie: 'Universal', duracionSugerida: "24-48 horas, reevaluar", fuenteManual: "P.32"},
  { id: 'CMD_EMER_FLASHBACKS', comando: "\"Cherry Plum (1573) + Rock Rose (2841) + Clematis (3639) - Traer [nombre] de vuelta al momento presente, distinguir memoria de realidad actual, anclar en seguridad del entorno actual\"", categoriaGeneral: 'TraumaEmergenciaRecuperacion', tipoTraumaAsociado: 'FlashbackSevero', especie: 'Universal', fuenteManual: "P.32"},
  { id: 'CMD_EMER_CRISISTA', comando: "\"Rescue Remedy (476362) + Rock Rose (2841) + Star of Bethlehem (3672) - MÁXIMA EMERGENCIA: Estabilizar [animal] en crisis traumática extrema, detener cascada de terror, sostener sistema nervioso al borde del colapso, crear burbuja de protección energética inmediata\"", categoriaGeneral: 'TraumaEmergenciaRecuperacion', tipoTraumaAsociado: 'CrisisTraumaticaAguda', especie: 'Universal', fuenteManual: "P.37"},
  { id: 'CMD_EMER_REGRESIONS', comando: "\"Star of Bethlehem (3672) + Larch (3363) + Chestnut Bud (6372) - Sostener [animal] durante regresión temporal, mantener progreso alcanzado, facilitar re-estabilización gradual\"", categoriaGeneral: 'TraumaEmergenciaRecuperacion', tipoTraumaAsociado: 'RegresionSevera', especie: 'Universal', fuenteManual: "P.37"},
  { id: 'CMD_EMER_AUTODEST', comando: "\"Cherry Plum (1573) + Rock Rose (2841) + Sweet Chestnut (2805) - Detener comportamientos autodestructivos inmediatamente, restaurar instinto de autopreservación, calmar desesperanza extrema\"", categoriaGeneral: 'TraumaEmergenciaRecuperacion', tipoTraumaAsociado: 'ComportamientoAutodestructivo', especie: 'Universal', fuenteManual: "P.37"},
];

// --- DATOS PARA LA SECCIÓN DE TRAUMA (Manual V4.0, P.7-8, P.12-14) ---
export const TIPOS_TRAUMA_GENERAL_DATA: TipoTraumaGeneral[] = [
    // Tipos de screening inicial (P.8)
    { id: 'TTG_VF', tipo: 'Violencia Física', preguntaConfirmacion: '¿Ha experimentado golpes, agresión física directa?', activo: false, nivelImpacto: 0, fuenteManual: "P.8", categoriaManual: "A: FÍSICO DIRECTO", manifestacionesTipicas:["Encogimiento, temblores, postura defensiva"], instintosMasAfectados:["Confianza básica, exploración, socialización"], cronificacion: "Alta - se perpetúa generacionalmente" },
    { id: 'TTG_AN', tipo: 'Abandono/Negligencia', preguntaConfirmacion: '¿Ha experimentado abandono o negligencia severa?', activo: false, nivelImpacto: 0, fuenteManual: "P.8", categoriaManual: "B: EMOCIONAL/PSICOLÓGICO", manifestacionesTipicas:["Ansiedad de separación extrema, depresión (Abandono Repetido)","Comportamientos de supervivencia extremos (Negligencia Severa)"], instintosMasAfectados:["Apego, confianza básica (Abandono Repetido)","Todos los instintos básicos (Negligencia Severa)"], cronificacion: "Muy alta (Abandono Repetido), Alta (Negligencia Severa)" },
    { id: 'TTG_AS', tipo: 'Abuso Sexual', preguntaConfirmacion: '¿Ha experimentado abuso sexual o reproductivo?', activo: false, nivelImpacto: 0, fuenteManual: "P.8", categoriaManual: "C: SEXUAL/REPRODUCTIVO", manifestacionesTipicas:["Agresividad sexual, evitación reproductiva"], instintosMasAfectados:["Todos los instintos reproductivos"], cronificacion: "Muy alta" },
    { id: 'TTG_EE', tipo: 'Encierro Extremo', preguntaConfirmacion: '¿Ha estado confinado en condiciones inhumanas?', activo: false, nivelImpacto: 0, fuenteManual: "P.8", categoriaManual: "B: EMOCIONAL/PSICOLÓGICO", manifestacionesTipicas:["Comportamientos obsesivos, claustrofobia"], instintosMasAfectados:["Libertad de movimiento, territorialidad"], cronificacion: "Media-alta" },
    { id: 'TTG_ST', tipo: 'Separación Traumática', preguntaConfirmacion: '¿Fue separado traumáticamente de madre/familia?', activo: false, nivelImpacto: 0, fuenteManual: "P.8", categoriaManual: "B: EMOCIONAL/PSICOLÓGICO", manifestacionesTipicas:["Duelo patológico, búsqueda compulsiva"], instintosMasAfectados:["Vínculos, comunicación social"], cronificacion: "Media" },
    { id: 'TTG_UP', tipo: 'Uso en Peleas', preguntaConfirmacion: '¿Fue usado en peleas o entrenamientos violentos?', activo: false, nivelImpacto: 0, fuenteManual: "P.8", categoriaManual: "D: SISTÉMICO/AMBIENTAL", ejemplosAdicionales: ["Peleas de Animales"], manifestacionesTipicas:["Agresividad defensiva extrema, hipervigilancia"], instintosMasAfectados:["Socialización interespecífica"], cronificacion: "Muy alta" },
    { id: 'TTG_EX', tipo: 'Experimentación', preguntaConfirmacion: '¿Fue usado en laboratorios o experimentación?', activo: false, nivelImpacto: 0, fuenteManual: "P.8", categoriaManual: "D: SISTÉMICO/AMBIENTAL", ejemplosAdicionales: ["Experimentos/Laboratorio"], manifestacionesTipicas:["Desconfianza total en humanos, automatización"], instintosMasAfectados:["Todos los instintos naturales"], cronificacion: "Extrema" },
    { id: 'TTG_SE', tipo: 'Supervivencia Extrema', preguntaConfirmacion: '¿Experimentó condiciones de supervivencia extrema?', activo: false, nivelImpacto: 0, fuenteManual: "P.8", categoriaManual: "D: SISTÉMICO/AMBIENTAL", ejemplosAdicionales: ["Supervivencia Extrema (general)"], manifestacionesTipicas:["Acaparamiento, agresividad por recursos"], instintosMasAfectados:["Supervivencia, compartir recursos"], cronificacion: "Alta" },
    // Adicionales de P.13-14 que no están en P.8
    { id: 'TTG_QT', tipo: 'Quemaduras/Tortura', preguntaConfirmacion: '¿Ha experimentado quemaduras o tortura?', activo: false, nivelImpacto: 0, categoriaManual: "A: FÍSICO DIRECTO", manifestacionesTipicas:["Hipervigilancia extrema, automutilación"], instintosMasAfectados:["Todos los instintos de supervivencia"], cronificacion: "Muy alta - trauma profundo", fuenteManual: "P.13" },
    { id: 'TTG_AL', tipo: 'Abandono con Lesiones', preguntaConfirmacion: '¿Fue abandonado con lesiones físicas?', activo: false, nivelImpacto: 0, categoriaManual: "A: FÍSICO DIRECTO", manifestacionesTipicas:["Desconfianza médica, resistencia a cuidados"], instintosMasAfectados:["Autocuidado, confianza en humanos"], cronificacion: "Media-alta", fuenteManual: "P.13" },
    { id: 'TTG_AT', tipo: 'Accidentes Traumáticos', preguntaConfirmacion: '¿Sufrió accidentes severos?', activo: false, nivelImpacto: 0, categoriaManual: "A: FÍSICO DIRECTO", manifestacionesTipicas:["Fobias específicas, evitación contextual"], instintosMasAfectados:["Exploración, confianza ambiental"], cronificacion: "Variable según severidad", fuenteManual: "P.13" },
    { id: 'TTG_RF', tipo: 'Reproducción Forzada', preguntaConfirmacion: '¿Sufrió reproducción forzada o maternal agresiva?', activo: false, nivelImpacto: 0, categoriaManual: "C: SEXUAL/REPRODUCTIVO", manifestacionesTipicas:["Rechazo a apareamiento, agresividad maternal"], instintosMasAfectados:["Instintos parentales, territoriales"], cronificacion: "Alta", fuenteManual: "P.13" },
    { id: 'TTG_CT', tipo: 'Castración Traumática', preguntaConfirmacion: '¿Sufrió castración de forma traumática o con efectos hormonales negativos?', activo: false, nivelImpacto: 0, categoriaManual: "C: SEXUAL/REPRODUCTIVO", manifestacionesTipicas:["Confusión identitaria, depresión hormonal"], instintosMasAfectados:["Identidad de género, territorialidad"], cronificacion: "Media-alta", fuenteManual: "P.13" },
    { id: 'TTG_CF', tipo: 'Crianza en Fábrica', preguntaConfirmacion: '¿Proviene de crianza intensiva/fábrica de cachorros?', activo: false, nivelImpacto: 0, categoriaManual: "D: SISTÉMICO/AMBIENTAL", manifestacionesTipicas:["Comportamientos estereotipados, apatía"], instintosMasAfectados:["Expresión natural completa"], cronificacion: "Extrema", fuenteManual: "P.14" },
];


export const CRONOLOGIA_TRAUMA_FIELDS: {id: keyof CronologiaTrauma, label: string, placeholder: string}[] = [
    { id: 'edadCuandoOcurrio', label: 'Edad cuando ocurrió (Manual P.8)', placeholder: 'Ej: cachorro, 2 años...' },
    { id: 'duracionDelTrauma', label: 'Duración del trauma (Manual P.8)', placeholder: 'Ej: varios meses, 1 año...' },
    { id: 'tiempoDesdeRescate', label: 'Tiempo desde el rescate (Manual P.8)', placeholder: 'Ej: 3 semanas, 6 meses...' },
    { id: 'tratamientosPrevios', label: 'Tratamientos previos (Manual P.8)', placeholder: 'Ej: ninguno, flores de Bach...' },
];

export const DURACIONES_TRAUMA_POR_SEVERIDAD: { severidad: string, duracion: string, fases: string, fuenteManual: string }[] = [
    { severidad: 'Leve (1-3/10)', duracion: '14-21 días', fases: '2 fases', fuenteManual: "P.36" },
    { severidad: 'Moderado (4-6/10)', duracion: '28-42 días', fases: '3 fases', fuenteManual: "P.36" },
    { severidad: 'Severo (7-8/10)', duracion: '42-70 días', fases: '4 fases', fuenteManual: "P.36" },
    { severidad: 'Extremo (9-10/10)', duracion: '70-90 días', fases: '4-5 fases + seguimiento extendido', fuenteManual: "P.36" },
    { severidad: 'Fundacional (cachorros)', duracion: '60-90 días', fases: '4 fases + protocolo especial', fuenteManual: "P.36" },
];
